kind: pipeline
name: default

steps:
- name: prepare
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter packages get

- name: format
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter format --dry-run --set-exit-if-changed .

- name: analyze
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter analyze

- name: test
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - pushd example/
  - flutter test

#- name: proguard
#  image: v7lin/flutter:1.5.4-hotfix.2-stable
#  volumes:
#  - name: pub-cache
#    path: /opt/flutter/.pub-cache
#  commands:
#  - pushd example/
#  - flutter build apk

- name: publish-check
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter packages pub publish --dry-run

volumes:
- name: pub-cache
  temp: {}
